### ISSUE TITLE
Create an Azure DevOps extension (just like the GitHub Action)

### ISSUE THREAD

**Issue by dgcaron** [infracost/infracost-azure-devops#4]
this is more a question than an issue but are there any plans? and if so, would this be the repo that would be used for this?

**Comment by dgcaron** [comment]
sure, i'll clean some stuff up and create a PR. everything is pretty straightforward so I assume a call wouldn't be necessary.

**Comment by dgcaron** [comment]
PR is opened at #5

**Comment by alikhajeh1** [comment]
This is being worked on by @hugorut and @vdmgolub :)

**Comment by hugorut** [comment]
Hey @dgcaron, I'm going to close this as we now have some shiny new tasks that come as part of our official Azure Devops Extension. You can view it here: https://marketplace.visualstudio.com/items?itemName=Infracost.infracost-tasks . Thanks again for all your help with this 🚀  ❤️

**Comment by dgcaron** [comment]
Great stuff!! Congrats
