### ISSUE TITLE
Pipeline breakdown & diff task issue

### ISSUE THREAD

**Issue by majorku5anagi** [infracost/infracost-azure-devops#65]
Hi, it seems to me that part of the template pipeline about preparing to perform `diff` operation is somewhat wrong as it looks like that pipeline is firstly performing the `breakdown` againts `TF_ROOT` path and outputting it to `.json` file which is followed by `diff` operation using again `TF_ROOT` path and same `.json` file from the previous step. This is causing the report to say there is no change.

Suggestion could be to use 2 separate variables, `TF_ROOT_OLD` and `TF_ROOT_NEW` like in the screenshot below. `TF_ROOT_OLD` will be targeting the `tmp/base` path that contains the clone of the main branch that was done before the `breakdown` task (`git clone` task) and `TF_ROOT_NEW` will have the root of the already downloaded dev branch in the first steps of the pipeline (automatic).

![image](https://user-images.githubusercontent.com/87762615/183072398-f0120f9e-96b1-4962-8561-c7082a0828a4.png)

![image](https://user-images.githubusercontent.com/87762615/183073675-d8f01e5b-ad73-4042-955e-107ad628de0f.png)

**Comment by aliscott** [comment]
Thanks @majorku5anagi, nicely found and investigated 🙌 ! I've pushed a fix in https://github.com/infracost/infracost-azure-devops/pull/66 so the example in the main README matches the [one here](https://github.com/infracost/infracost-azure-devops/tree/master/examples/terraform-project).
