### ISSUE TITLE
Task 'Infracost Setup Task' version 2 (InfracostSetup@2) is dependent on a Node version (10) that is end-of-life.

### ISSUE THREAD

**Issue by Stephani0106** [infracost/infracost-azure-devops#92]
Hello! 

We use Task `InfracostSetup@2` in our Azure DevOps pipelines and recently in the pipeline runs I was presented with the following error:

```bash
##[warning]Task 'Infracost Setup Task' version 2 (InfracostSetup@2) is dependent on a Node version (10) that is end-of-life.
Contact the extension owner for an updated version of the task. Task maintainers should review Node upgrade guidance:
https://aka.ms/node-runner-guidance
```

![image](https://github.com/user-attachments/assets/efe16736-cea3-46e6-ab19-ff1932db84be)

I believe that the Node version should be updated to version 20 or above within the [task.json](https://github.com/infracost/infracost-azure-devops/blob/master/tasks/InfracostSetup/task.json) file.

![image](https://github.com/user-attachments/assets/e54e6a84-37e7-478c-a072-73439f8b72f5)

Supported node versions documentation: https://nodejs.org/en/about/previous-releases

Could someone help us with this?

**Comment by aliscott** [comment]
Thanks @Stephani0106 🙏, this has been released in 2.1.0.
